# QUBO formulation of polynomial equation

In this notebook we show how to use `QUBOPS` to solve simple non linear system of equations. We start by defining our system of equations as follows:

$$
 0.5 - x_0^2 + x_1 = 0 
$$
$$
 1 - 2x_0 + x_1^2 = 0
$$


## Classical Newton Raphson solution 

We first solve this system using a Newton Raphson approach implemented in `scipy`. To use the newton raphson solver we need to define a function that returns the value of the non linear system for a given input. 


In [1]:
import numpy as np


def nlfunc(input):
    x0, x1 = input

    def f0():
        return 1 / 2 + x0**2 - x1

    def f1():
        return -1 + x0 + x1

    return np.array([f0(), f1()])

We can now solve the system using `scipy.optimize.newton` 

In [3]:
from scipy.optimize import newton
from quantum_newton_raphson.newton_raphson import newton_raphson

initial_point = np.random.rand(2)
ref_sol = newton_raphson(nlfunc, initial_point)

assert np.allclose(nlfunc(ref_sol), 0)

/home/nico/miniconda3/envs/vitens_wntr_1/lib/python3.9/site-packages/quantum_newton_raphson/utils.py:74: SparseEfficiencyWarning: spsolve requires A be CSC or CSR matrix format
  warn("spsolve requires A be CSC or CSR matrix format", SparseEfficiencyWarning)


TypeError: cannot unpack non-iterable NewtonRaphsonResult object

The solution of the system is therefore

In [5]:
ref_sol.solution

array([0.3660254, 0.6339746])

In [6]:
nlfunc(ref_sol.solution)

array([1.49534829e-11, 1.11022302e-16])

## Polynomial equation 

We first write the polynomial equation as follow (https://www.nature.com/articles/s41598-019-46729-0) 

$$
F(X) = 0
$$

with

$$
F_i = P_i^{(0)} + \sum_j P_{ij}^{(1)}x_j + \sum_{jk} P_{ijk}^{(2)}x_j x_k  + \sum_{jkl} P_{ijkl}^{(3)}x_j x_k x_l = 0
$$

To solve the system we minimize the residual sum of square

$$
\chi^2 = [P^{(0)} + P^{(1)} X + P^{(2)} X^2 + P^{(3)} X^3]^2
$$


We need to define the matrices $P_{ij...}^{(n)}$ for our system of equation

In [13]:
import sparse


def define_matrices():

    # system of equations
    num_equations = 4
    num_variables = 4

    P0 = np.zeros(num_equations)
    P0[0] = 1 / 2
    P0[1] = 1
    P0[2] = 3
    P0[3] = 0

    P1 = np.zeros((num_equations, num_variables))
    P1[0, 0] = -1
    P1[0, 1] = 1

    P1[1, 1] = -1

    P1[2, 2] = -1

    P1[3, 2] = 1
    P1[3, 3] = -1

    P2 = np.zeros((num_equations, num_variables, num_variables))
    P2[2, 0, 0] = -1
    P2[3, 1, 1] = -1 / 2

    return sparse.COO(P0), sparse.COO(P1), sparse.COO(P2)


matrices = define_matrices()

## Encoding

As for any QUBO approach, we need to encode the variables we are looking for in a series of qubit. Several encodings are possible. We here decide to use differnet encodings for the first and last two variables. We also decide to use here the `SteepestDescentSampler` to be able to run that code locally. Quantum solvers are available through the Leap cloud service.


In [14]:
from qubops.qubops_mixed_vars import QUBOPS_MIXED
from qubops.encodings import PositiveQbitEncoding
from qubops.solution_vector import SolutionVector_V2 as SolutionVector
from qubops.mixed_solution_vector import MixedSolutionVector_V2 as MixedSolutionVector
from dwave.samplers import SteepestDescentSolver


# define the encoding for the first two varialbes
nqbit = 5
step = 0.05
encoding1 = PositiveQbitEncoding(nqbit=nqbit, step=step, offset=0, var_base_name="x")
sol_vec1 = SolutionVector(2, encoding=encoding1)

# define the encoding for the alst two variables
nqbit = 4
step = 0.05
encoding2 = PositiveQbitEncoding(nqbit=nqbit, step=step, offset=0, var_base_name="x")
sol_vec2 = SolutionVector(2, encoding=encoding2)

# define the solution vector
sol_vec = MixedSolutionVector([sol_vec1, sol_vec2])

# instantiat the QUBOPS solver
options = {"num_reads": 10000, "sampler": SteepestDescentSolver()}
qubo = QUBOPS_MIXED(sol_vec, options)

We can check which values are possible for the different encodings:

In [15]:
np.sort(encoding1.get_possible_values())

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  , 1.05,
       1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 , 1.55])

In [16]:
np.sort(encoding2.get_possible_values())

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75])

## Solving the system

We can now solve the system and analyze the solution

In [ ]:
sol = qubo.solve(matrices, strength=1e5)
sol = np.array(sol).reshape(-1)

data_ref, eref = qubo.compute_energy(ref_sol)
data_sol, esol = qubo.compute_energy(sol)

print(ref_sol, eref)
print(sol, esol)

[1.5  1.   0.75 0.25] -10.250000000000002
[1.5  1.   0.75 0.25] -10.250000000000002
